workflows:
  unsigned-ios-build:
    name: Unsigned iOS Build
    environment:
      flutter: "3.19.6" # or any stable version
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build unsigned iOS app
        script: flutter build ios --release --no-codesign

      - name: Create .ipa (manual payload zip)
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r UnsignedRunner.ipa Payload

    artifacts:
      - build/ios/iphoneos/UnsignedRunner.ipa
